---
- name: Install Kubernetes on Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/$(lsb_release -cs) main"
        state: present

    - name: Download Google Cloud public signing key
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Mark kubelet to hold its version
      command: apt-mark hold kubelet

    - name: Mark kubeadm to hold its version
      command: apt-mark hold kubeadm

    - name: Mark kubectl to hold its version
      command: apt-mark hold kubectl

    - name: Disable swap (required by Kubernetes)
      command: swapoff -a
      ignore_errors: yes

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*'
        state: absent

    - name: Initialize Kubernetes cluster (control plane only)
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: kubeadm_init
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Set up kubeconfig for the ubuntu user
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - sudo chown $(id -u):$(id -g) $HOME/.kube/config
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Install a pod network add-on
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Allow scheduling on the master node (optional)
      command: kubectl taint nodes --all node-role.kubernetes.io/master-
      when: inventory_hostname == groups['k8s_master'][0]
